# Process a single image pair
name: Single
run-name: ${{ inputs.workflow_name }}

# Set workflow input parameters and defaults
on:
  workflow_dispatch:
    inputs:
        reference:
            type: string
            required: true
            description: Reference SLC
            default: S1_136231_IW2_20200604T022312_VV_7C85-BURST
        secondary:
            type: string
            required: true
            description: Secondary SLC
            default: S1_136231_IW2_20200616T022313_VV_5D11-BURST
        looks:
            type: choice
            required: true
            description: Range x Azimuth Looks
            default: 20x4
            options: ['20x4', '10x2', '5x1']
        apply_water_mask:
            description: 'Apply a water mask'
            required: true
            default: false
            type: boolean
        workflow_name:
            description: 'Custom workflow name'
            required: false
            default: 'Hyp3-ISCE2'
            type: string

  # Must duplicate inputs for workflow_call (https://github.com/orgs/community/discussions/39357)
  workflow_call:
    inputs:
        reference:
            type: string
            description: Reference SLC
        secondary:
            type: string
            description: Secondary SLC
        looks:
            type: string
            description: Range x Azimuth Looks
        apply_water_mask:
            description: 'Apply a water mask'
            type: boolean
        workflow_name:
            description: 'Custom workflow name'
            type: string

jobs:
    hyp3-isce2:
        name: ${{ inputs.workflow_name }}
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -el {0}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install Conda environment with Micromamba
              uses: mamba-org/setup-micromamba@v1
              with:
                cache-environment: true
                environment-file: conda-lock.yml
                environment-name: hyp3-isce2

            # NOTE: be sure to share Organization Secrets with this repository
            - name: Run Hyp3-ISCE2 Software
              env: 
                EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
                EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD}}
                ESA_USERNAME: ${{ secrets.ESA_USERNAME }}
                ESA_PASSWORD: ${{ secrets.ESA_PASSWORD}}
              run: |
                python -m hyp3_isce2 ++process insar_tops_burst \
                    ${{ inputs.reference }} \
                    ${{ inputs.secondary }} \
                    --looks ${{ inputs.looks }} \
                    --apply-water-mask ${{ inputs.apply_water_mask }} 

            - name: Upload Hyp3-ISCE2 Output Folder
              uses: actions/upload-artifact@v4
              with:
                name: ${{ inputs.workflow_name }}
                # Exclude redundant zipped output folder from hyp3-isce2
                path: |
                    S1_*INT*
                    !S1_*ZIP
